### ISSUE TITLE
High level definition of the Aurelia-Syncfusion project 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#1]
#### This definition of the project  is a proposal by Aurelia-UI-Toolkits team. Before it gets accepted in its original or modified form, it has to thoroughly vetted and approved by Syncfusion team

Please post your comments, as additional comments to this issue.

**Comment by adriatic** [comment]
### High level definition of Aurelia-Syncfusion bridge project

Aurelia-Syncfusion bridge is a special type of an Aurelia application -  **Aurelia plugin**, term defined by the following paragraph:

> Aurelia integrates well with 3rd party libraries. Just jspm install the library you want to use, import it in your JavaScript module and then start coding with it. Some libraries may be built specifically for Aurelia. As a developer, you use those in the same way: install, import and code. However, the author of an Aurelia-specific library may choose to take advantage of our plugin model. By implementing a library as a plugin, the plugin author has the opportunity to run code as part of Aurelia's startup sequence, before anything is rendered. A plugin is provided with the same FrameworkConfiguration instance that is available to the app developer during the bootstrapping phase. As a result, a plugin can configure Aurelia in any way it wants. Typical tasks for a plugin might be to register services in the dependency injection container or customize some part of Aurelia's configuration. They might even do feature detection and install polyfills where appropriate.

In order to dramatically simplify the support for testing the bridge at the same time it is being developed , Aurelia-Syncfusion bridge is designed as a **composite application**: the **_bridge plugin**_ and the **_catalog application**_, both being a part of the same repository, sharing the private "connection" between them. So, the typical task of **_adding**_ a Syncfusion widget consists of the following steps:
1. Create the Aurelia **_widget wrapper**_ and add it to the bridge (plugin). This process makes the original widget available to the application developer as fully conformant Aurelia **_component.**_
2. Create the sample Aurelia applet which fetches this new widget packaged as a component and shows all interesting aspects of this component on a single page of.  above mentioned **_catalog application**_ . This catalog application is  the (equivalent) Aurelia version  of Syncfusion's **[Essential JS Showcase samples](http://js.syncfusion.com/demos/web/)** web application.

See  **[quick bridge developer's tutorial](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/quick-bridge-developer's-tutorial)** document for more detailed description of the this two step process:

---

The following two images show this suggested equivalence. Note that the second image will be replaced with Syncfusion Rich Text Editor **widget** converted to Aurelia **component**.

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/14233047/3f58b7d0-f98b-11e5-8eef-5443fce0bcb4.png"></img>
 <br><br>
Syncfusion Rich Text Editor widget
</p>

<br>

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/14233054/667e9ef6-f98b-11e5-8a5c-fd124131ab0c.png"></img>
 <br><br>
KendoUI Rich Text Editor component
</p>

**Comment by bharathm03** [comment]
@adriatic this definition document is fine for us.

**Comment by adriatic** [comment]
Wonderful - I really appreciate having each issue (like this one) concluded with the confirmation that all is fine :-)
