### ISSUE TITLE
Nik's feedback on 4/25/2015

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#17]
In general, I believe that this bridge is moving in the right direction, although slower than I expected. Here are more detailed questions / comments - please answer each of them in the comments to this article.
### Question 1

**Do you feel that you need more help from Aurelia-UI-Toolkits team?**
### Question 2

**Are you aware of the Aurelia Component Lifecycle?**

> I mentioned several times that the implementation of all wrappers ([button](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/tree/master/src/button), [checkbox](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/tree/master/src/checkbox), [menu](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/tree/master/src/menu)) are incomplete as they are not implementing all needed callbacks - they all only have constructors, missing `bind`, `attached` and `detached` callback. In my opinion, it does not make sense to leave one wrapper code unfinished and going to work on the next. 
> 
> As a part of your work, you need to read the Aurelia official documentation - and in this particular situation the read the whole section [4. Creating Components](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.2/doc/article/creating-components), please
### Question 3

**Do you plan to implement [KendoUI catalog application](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/18)'s navigation design?**

> We would expect that you will answer **YES**  to this question, but you may discuss it with the development management before answering it. Please be sure that this is a very important decision to make at this point as you are deviating from our proposed navigation design.
> 
> ![image](https://cloud.githubusercontent.com/assets/2712405/14792715/974dcfa6-0ae9-11e6-8e7a-88ea986f7534.png)

**Comment by bharathm03** [comment]
@adriatic Thank you for your feedbacks. Please find my answers to comments and questions

Question 1:
No, you already provided sufficient information to complete the bridge.

Question 2:
Yes, we aware of Aurelia component lifecycle. Also, we implemented those for all the completed components (button, checkbox, menu). The lifecycle functions [attached](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/blob/master/src/common/widget-base.js#L59), [detached ](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/blob/master/src/common/widget-base.js#L87)are moved to [`WidgetBase`](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/blob/master/src/common/widget-base.js#L4) class which are [inherited ](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/blob/master/src/button/button.js#L14)by all the wrappers. 

Question 3:
Yes, we will implement the kendo like proposed navigation for Syncfusion Catalog application. Also, we have finalized our controls and its category in Catalog application. Please find the same in following list

Grids
1.  Grid
2.  TreeGrid
3.  Spreadsheet

Data Visualization
1.  Chart
2.  Gantt
3.  Schedule
4.  Diagram
5.  Maps
6.  Tree Map
7.  Circular Gauge
8.  Linear Gauge
9.  Digital Gauge
10. Bullet Graph
11. Range Navigator
12. Barcode
13. TagCloud
14. Kanban Board

File Viewer
1.  Pdf Viewer

Layout
1.  Splitter
2.  Dialog
3.  ListView
4.  TileView

Editors
1.  RichTextEditor
2.  ColorPicker
3.  DatePicker
4.  TimePicker
5.  DateTimePicker
6.  TextBoxes
7.  Autocomplete
8.  RadialSlider
9.  Rating
10. DropDownList
11. Slider
12. Button
13. Checkbox
14. RadioButton
15. Uploadbox

Miscellaneous
1.  DataManager
2.  Calculate

Navigation
1.  Ribbon
2.  RadilaMenu
3.  FileExplorer
4.  TreeView
5.  Rotator
6.  Tab
7.  Menu
8.  Accordion
9.  ListBox
10. Toolbar
11. Scrollbat
12. NavigationDrawer

Notification
1.  Progressbar
2.  WaitingPopup
3.  ToolTip

**Comment by adriatic** [comment]
Certainly a good list of categories - in the best case you should map the complete **[EJ demo site](http://js.syncfusion.com/demos/web/)** into the layout for **[Aurelia Kendo Catalog app](http://aurelia-ui-toolkits.github.io/demo-kendo/)** 

Observe the "smooth navigation" to any example, where you have the complete breadcrumb feature implemented by showing the selected menu and additional toolbar items that led you to the component of interest:

![image](https://cloud.githubusercontent.com/assets/2712405/14826061/45714bf6-0baa-11e6-9a0c-c3e58ca9cb35.png)

Please plan for the two newly added features, invoked by RUN and API buttons. The first invokes the "real time" Aurelia component runner, and the second show the original Syncfusion API for that specific component.

![image](https://cloud.githubusercontent.com/assets/2712405/14826165/a2964bb0-0baa-11e6-925c-e503c91a3dd2.png)

**Comment by bharathm03** [comment]
Yes @adriatic we will add samples for all the Syncfusion JavaScript controls in the proposed layout. and I will ensure that breadcrumb is implemented properly for catalog application. 

We have planned to support Run and API button feature at later stage. Also for easier tracking, I have created new issue for the same

https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/20

**Comment by adriatic** [comment]
Great!

**Comment by karthickthangasamy** [comment]
The breadcrumb implemented for [demo-syncfusion](http://aurelia-ui-toolkits.github.io/demo-syncfusion/) catalog.
