### ISSUE TITLE
Navigation for catalog application

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#18]
We use the name "catalog application" as the reference to Aurelia implementation of the original [Syncfusion demo application](http://js.syncfusion.com/demos/web/)

The design we created for Aurelia version of the original seems easier to navigate - as shown on the image below. Since the Syncfusion demo application is nearly identical to the KendoUI, it seems logical that Aurelia-Syncfusion catalog app implements the same design

![image](https://cloud.githubusercontent.com/assets/2712405/14792277/8753fca8-0ae7-11e6-9b3f-c675654e0fea.png)

**Comment by karthickthangasamy** [comment]
The proposed navigation implemented for [demo-syncfusion](http://aurelia-ui-toolkits.github.io/demo-syncfusion/) catalog.
