### ISSUE TITLE
Need to implement RUN and API buttons for catalog application

### ISSUE THREAD

**Issue by bharathm03** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#20]
> Please plan for the two newly added features, invoked by RUN and API buttons. The first invokes the "real time" Aurelia component runner, and the second show the original Syncfusion API for that specific component.

![Image](https://cloud.githubusercontent.com/assets/2712405/14826165/a2964bb0-0baa-11e6-925c-e503c91a3dd2.png)

**Comment by karthickthangasamy** [comment]
The `RUN` and `API` buttons implemented.

Demo link: http://aureliajq.syncfusion.com/

**Comment by adriatic** [comment]
Thank you Syncfusion team on following through on my suggestions. It is really cool to offer the Aurelia Community the standardized AP across several UI toolkits.
