### ISSUE TITLE
Need to add user `syncfusion-javaScript` in aurelia-ui-toolkit organisation

### ISSUE THREAD

**Issue by bharathm03** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#24]
@adriatic we have planned to auto deploy the source/samples changes into `aurelia-syncfusion-bridge` after every Essential Studio release. For this purpose, we have planned to use the github username @syncfusion-javascript. So can you please add this username into `aurelia-ui-toolkit` organisation with write permission?

**Comment by karthickthangasamy** [comment]
@adriatic please add @syncfusion-javascript username also in NPM owner's list.
