### ISSUE TITLE
Some SyncFusion Controls stop to work after Aurelia RC1

### ISSUE THREAD

**Issue by fhjuliao** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#32]
Some controls, like GRID, does not work with aurelia RC1 release. After some research, I think Thanood pull resquest, can solve the issue.

Do you have some update about when the pull request made by him will be done ?

Thank you.

Fabio Julião

**Comment by karthickthangasamy** [comment]
@fhjuliao `aurelia-syncfusion-bridge` now supports **Aurelia RC**.
