### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by johntom** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#34]
Hi,
Using skeleton-esnext as base I've successfully installed Aurelia-Materialize bridge and aurelia-ui-toolkits/aurelia-v-grid and have most of the demo-syncfusion working (about/help don't display). I get the following errors when installing this plugin changing only the following version references from the in config.js
  "jquery": "npm:jquery@2.2.4",
  "jquery-easing": "npm:jquery.easing@1.4.1",
  "jquery-validation": "npm:jquery-validation@1.15.1",

When I add .plugin('aurelia-syncfusion-bridge', plugin => plugin.useAll()) I get..
The installed path looks fine
C:\aureliaTut\skeleton-navigation-materializeV2\jspm_packages\github\syncfusion\JavaScript-Widgets@14.2.26\Scripts\ej\web\ej.accordion.min.js...

system.src.js:5123 GET http://localhost:9000/dist/datavisualization/ej.chart.min.js 404 (Not Found)Z @ system.src.js:5123(anonymous function) @ system.src.js:5123e._execute @ bluebird.min.js:31i._resolveFromExecutor @ bluebird.min.js:32i @ bluebird.min.js:32(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123r @ bluebird.min.js:33i._settlePromiseFromHandler @ bluebird.min.js:32i._settlePromise @ bluebird.min.js:32i._settlePromise0 @ bluebird.min.js:32i._settlePromises @ bluebird.min.js:32r._drainQueue @ bluebird.min.js:31r._drainQueues @ bluebird.min.js:31drainQueues @ bluebird.min.js:31
bluebird.min.js:31 Unhandled rejection Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:9000/dist/datavisualization/ej.chart.min.js
    Error loading http://localhost:9000/dist/datavisualization/ej.chart.min.js as "datavisualization/ej.chart.min" from http://localhost:9000/jspm_packages/npm/aurelia-syncfusion-bridge@0.2.0/chart/chart.js
system.src.js:5123 GET http://localhost:9000/dist/ej.grid.min.js 404 (Not Found)Z @ system.src.js:5123(anonymous function) @ system.src.js:5123e._execute @ bluebird.min.js:31i._resolveFromExecutor @ bluebird.min.js:32i @ bluebird.min.js:32(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123r @ bluebird.min.js:33i._settlePromiseFromHandler @ bluebird.min.js:32i._settlePromise @ bluebird.min.js:32i._settlePromise0 @ bluebird.min.js:32i._settlePromises @ bluebird.min.js:32r._drainQueue @ bluebird.min.js:31r._drainQueues @ bluebird.min.js:31drainQueues @ bluebird.min.js:31
..
John

**Comment by JeroenVinke** [comment]
Hey John,

did you add the `"datavisualization/ej.*"` mapping to your config.js? Should be done in step 3 of JSPM or step 4 of vendors

**Comment by johntom** [comment]
Yes, I followed instructions and did it a few times to make sure I didn't skip something

System.config({
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "_": "dist/_",
    "github:_": "jspm_packages/github/_",
    "npm:_": "jspm_packages/npm/_",
    "common/ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.1.0.41/scripts/ej/common/ej._.js",
    "datavisualization/ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.1.0.41/scripts/ej/datavisualization/ej._.js",
    "ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.1.0.41/scripts/ej/web/ej._.js",
    "syncfusion-javascript/_": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.1.0.41/_"
  },
  map: {
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-rc.1.0.0",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-rc.1.0.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-rc.1.0.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-rc.1.0.6",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-rc.1.0.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-rc.1.0.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-rc.1.0.0",
    "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge@0.10.3",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-rc.1.0.0",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-rc.1.0.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-rc.1.0.1",
    "aurelia-syncfusion-bridge": "npm:aurelia-syncfusion-bridge@0.2.0",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-rc.1.0.0",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-rc.1.0.0",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-rc.1.0.0",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-rc.1.0.0",
    "aurelia-v-grid": "github:aurelia-ui-toolkits/aurelia-v-grid@0.2.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bluebird": "npm:bluebird@3.4.1",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "clean-css": "npm:clean-css@3.4.18",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.23",
    "fetch": "github:github/fetch@1.0.0",
    "font-awesome": "npm:font-awesome@4.6.3",
    "jquery": "npm:jquery@2.2.4",
    "jquery-easing": "npm:jquery.easing@1.4.1",
    "jquery-validation": "npm:jquery-validation@1.15.0",
    "jquery-validation-unobtrusive": "npm:jquery-validation-unobtrusive@3.2.6",
    "json": "github:systemjs/plugin-json@0.1.2",
    "jsrender": "npm:jsrender@0.9.79",
    "materialize": "github:Dogfalo/materialize@0.97.6",
    "syncfusion-javascript": "github:syncfusion/JavaScript-Widgets@14.2.26",
    "systemjs/plugin-text": "github:systemjs/plugin-text@0.0.8",
    "text": "github:systemjs/plugin-text@0.0.8",

**Comment by JeroenVinke** [comment]
Strange, can you compare your setup to https://github.com/JeroenVinke/syncfusion-test ? that one is working for me

**Comment by johntom** [comment]
Will do

**Comment by johntom** [comment]
Just installed and the test (select box) is working. I will install a grid
example and do a beyon compare and get back to you

**Comment by johntom** [comment]
Just import images and scripts directory and grid displays EmployeesList
Now for compare

**Comment by johntom** [comment]
Well, I thought I dotted all my i's but it turns out I had bad version references in config,sys, simple replace with the following fixed.  As an aside, I have a license of KendoUI Pro but I seem to prefer suncfusion the the declarative nature using html vs code with my first analysis.
Sorry for the delay and thanks for your help!
John
Changed the following based on test repo 
 "common/ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.2.26/scripts/ej/common/ej._.js",
    "datavisualization/ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.2.26/scripts/ej/datavisualization/ej._.js",
    "ej._": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.2.26/scripts/ej/web/ej._.js",
    "syncfusion-javascript/_": "jspm_packages/github/syncfusion/JavaScript-Widgets@14.2.26/_"

**Comment by karthickthangasamy** [comment]
@johntom Sorry for the late response. You can use the below repository which was configured for `aurelia-syncfusion-bridge` to avoid installation and configuration issues.

Repository : https://github.com/aurelia-ui-toolkits/syncfusion-template-repository

**Comment by adriatic** [comment]
@johntom 

> I seem to prefer suncfusion the the declarative nature using html vs code 

I am curious about this statement since KendoUI and Syncfusion are very similar products from the Aurelia's prospective and should offer the same level of support for declarative programming model. Can you give me some examples?

**Comment by johntom** [comment]
Quick assesment with setting up grid, In Kendo (angular and aurelia) all my
setup is in code (never tried in html and don't recall any docs on showing
this) and out of the gate I have the following in html. I also find the
databing sinplier to read and setup.
All things considered they seem quite similar but I always found kendo a
bit of a pain and only use the grid for analysis.

<div>
       <ej-grid e-data-source.bind="EmployeesList"
e-page-settings.bind="page" e-allow-paging=true
 e-edit-settings.bind="edit" e-toolbar-settings.bind="toolbar">
            <ej-column e-field="EmployeeImage" e-header-text="Employee
Image" e-text-align="center" e-width="110">
                <ej-template>
                    <div><img style="width: 75px; height: 70px"
src="images/grid/Employees/${EmployeeID}.png" /> </div>

```
            </ej-template>
        </ej-column>
        <ej-column e-field="EmployeeID" e-header-text="Employee ID"
```

e-text-align="right" e-width="90"></ej-column>
            <ej-column e-field="FirstName" e-header-text="First Name"
e-width="90"></ej-column>
            <ej-column e-field="LastName" e-header-text="Last Name"
e-width="90"></ej-column>
            <ej-column e-field="BirthDate" e-header-text="Birth Date"
e-format="{0:MM/dd/yyyy}" e-text-align="right" e-width="90"></ej-column>
            <ej-column e-field="Country" e-header-text="Country"
e-width="80"></ej-column>
 <ej-column        e-header-text= "Manage Records"   e-width="80"

> </ej-column>
>         </ej-grid>
>     </div>

**Comment by adriatic** [comment]
I do not want to argue in favor of one of our bridges over the other one - so just for completeness sake, have a look at http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/grid/basic-use and see that the declarative part:

```
<template>
    <require from="./basic-use.css"></require>

    <ak-grid k-data-source.bind="datasource" k-pageable.bind="pageable" k-sortable.bind="true">
      <ak-col k-title="Contact Name" k-field="ContactName">
        <ak-template>
          <div class='customer-photo' style="background-image: url(http://demos.telerik.com/kendo-ui/content/web/Customers/${CustomerID}.jpg);"></div>
          <div class='customer-name'>${ContactName}</div>
        </ak-template>
      </ak-col>
      <ak-col k-title="Contact Name" k-field="ContactName"></ak-col>
      <ak-col k-title="Contact Title" k-field="ContactTitle"></ak-col>
      <ak-col k-title="Company Name" k-field="CompanyName"></ak-col>
      <ak-col k-field="Country"></ak-col>
    </ak-grid>
</template>
```

sets up most of grid's values except `pageable`, which being a composite attribute is easier (less verbose) defined in the view model.

**Comment by johntom** [comment]
Thanks, While I do use kendoui in my apps this is the first time I recall
seeing this example as I propably just ported my Angular examples over and
did tale a close look. Really great stuff  and find it much better to
organize code/html this way.  I can see the use of v-grid and kendo or
syncfusion So yes they are very similar and capable. I decided to
test syncfusion as a suggestion from Vegar. Is there a gist for syncfusion?
I have an open question about getting the same behavor for syncfusion as in
this gist.

**Comment by johntom** [comment]
https://gist.run/?id=8a50734f4d26a8ed163c41ebf9fb78f7

**Comment by adriatic** [comment]
@johntom 

> Is there a gist for syncfusion?

Not in this current release - I am just suggesting to  Syncfusion's management team to consider this upgrade next. Note that unlike KendoUI bridge's and Materialize bridge's cases where Aurelia-UI-Toolkit did all of the development, it was Syncfusion's development team that created the Syncfusion bridge using our bridge building infrastructure and our guidance on how to use it.
