### ISSUE TITLE
Is there a property that exposes the widget?

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#38]
In the Kendo-UI bridge, there is a "k-widget" that is useful to get at the underlying control.

`<ak-treeview k-data-source.bind="dataSource" k-widget.bind="treeView"></ak-treeview>`

I can then use "treeView" in the code behind so I can call methods, properties etc.

Is there a similar one for Syncfusion?

**Comment by adriatic** [comment]
As far as I remember, we introduced the k-widget **after** Syncfusion bridge was built (by Syncfusion team, using our technology and guidance. 

Let's see of some of the Syncfusion team responds to this question.

**Comment by karthickthangasamy** [comment]
Right now there is no option like `k-widget` in Syncfusion bridge. But you can get the underlying control data object in jquery approach, using the object you can invoke the methods and properties.

```
let obj = $("#treeview").data("ejTreeView");
obj.method();
```

Reference link : https://help.syncfusion.com/js/invoking-methods

**Comment by karthickthangasamy** [comment]
@JeroenVinke Could you please share the `k-widget` property bridge developer notes?

**Comment by JeroenVinke** [comment]
Sure, i'll write them up in the next few days

**Comment by JeroenVinke** [comment]
@Karthick-NR here I have added the notes: https://aurelia-ui-toolkits.gitbooks.io/kendoui-bridge-docs-beta/content/k-widget.html

**Comment by gregoryagu** [comment]
Any progress on this?

**Comment by karthickthangasamy** [comment]
@gregoryagu aurelia-syncfusion-bridge@0.5.0 release with `e-widget` property.

```javascript
//attached with TaskQueue
    attached() {
        this.taskQueue.queueTask(() => {
            setTimeout(() => {                
                console.log(this.grid);
            }, 1);
        });
    }

```
```javascript
//attached with setTimeout 
attached() {
        setTimeout(()=>{
            console.log(this.grid);
        },50)
    }

```

```javascript
//Event handler of ejGrid
    recordClick(e) {
        console.log(this.grid);
    }

```
