### ISSUE TITLE
Typescript declarations refer to a wrong *.d.ts

### ISSUE THREAD

**Issue by karthickthangasamy** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#39]
Typescript declaration is refer to kendoui bridge source, which is fixed [here](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/commit/2e285380e3eab7aadf74ebf65da3a17a2364184b).

Need to publish the changes into npm repository.

**Comment by JeroenVinke** [comment]
Released 0.2.1

**Comment by karthickthangasamy** [comment]
Thanks @JeroenVinke :+1:
