### ISSUE TITLE
Is there support for Aurelia style templates?

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#44]
I am using the TreeView control with a template like this:

```
     <div ref="treeViewDiv"
            ej-tree-view="e-fields.bind: { text: 'name'}; e-template.bind:'#templateData'">

        </div>
        <script id="templateData" type="text/x-jsrender">
            <a class="e-link" href="#/entity-shell/entities/{{>id}}">
                <b>{{>name}}</b><br />
            </a>
        </script>

```

But it would be nice to do the template Aurelia style:

```
<div ref="treeViewDiv"
            ej-tree-view="e-fields.bind: { text: 'name'}; ">
            <ej-template>
                 <a class="e-link" href="#/entity-shell/entities/${id}">
                <b>${name}</b><br />
            </a>
            </ej-template>
        </div>
```

The Kendo UI bridge has such a template and it works well.

**Comment by adriatic** [comment]
Aurelia Syncfusion bridge is "one generation" behind the current KendoUI bridge (both are built on AureliaTools infrastructure), so not all features from the latter bridge exist in the former. The future evolution of the Syncfusion bridge is defined by Syncfusion management, as it is their team who implemented (and supports) the Syncfusion bridge.

The relationship between the *native" templates and Aurelia templates is particularly thorny, as it is limited by the support from the native SDK (example: is it possible to turn off the native templating before turning on Aurelia templating; this was very difficult to do with KendoUI bridge and we managed to cover a small subset of all area of interest).

**Comment by gregoryagu** [comment]
Interesting.  Indeed, it is not an important issue - the templates do work well just as they are.

Thanks for the information.  Feel free to close this as desired.

**Comment by gregoryagu** [comment]
I found one thing that I don't like about the Syncfusion style templates is that it is only a template, it doesn't bind the data.  

So if the value of the underlying property changes, the UI doesn't update like it would if it were an Aurelia style template.   The only way I know to update is recreate the TreeView from scratch. Or perhaps there is a one to find the node and update.  In any case, if it were bound, it would not be an issue.

**Comment by AlainBaslter** [comment]
Oh I just ran into something similar. The two ejCheckBoxes in the show case samples were both bound  to the same view model property (checked). I expected their states to be synchronized. There were not.
the binding was ej-checked.bind=checked. I changed that to ej-checked.two-way and they worked as expected. I don't know your usage context but perhaps you are running into it. If you look at the generateBindings it appears that this would be two way bound automatically ['checked'] but apparently not as I just discovered.

**Comment by gregoryagu** [comment]
There is a way to use Aurelia binding in templates.  I found this in the dropdown example which uses Aurelia binding. The template was created in the javascript:

`this.template = '<div><img class="eimg" src="images/Employees/${eimg}.png" alt="employee"/>' + '<div class="ename"> ${text} </div><div class="desig"> ${desig} </div><div class="cont"> ${country} </div></div>';
`
