### ISSUE TITLE
binding for currencytextbox.decimal places not working

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#46]
I am using the currency textbox.  Overall, it works fine.  The value and width bind just fine.

But binding the decimal places does not seem to work for me.  This is the html:

`         <input id="currency" type="text" ej-currency-textbox="e-value.two-way:controller.item.cost;e-width.bind:'100%';e-decimalPlaces.bind:4" />
   `

I looked at the code in currencytextbox.js in aurelia.syncfusion-bridge and I can see the property there.  So I don't understand why it would not work.

Any advice would be appreciated.

**Comment by gregoryagu** [comment]
Ah, I got this to work.  The syntax should be `e-decimal-places.bind:4`,not `e-decimalPlaces:bind:4`

**Comment by AlainBaslter** [comment]
Is this part really working for you?
`ej-currency-textbox="e-value.two-way:controller.item.cost;"`

That's nested two deep: `controller.item.cost`
Are you sure its working? I can't seem to get nested properties to bind!
