### ISSUE TITLE
ejGrid events

### ISSUE THREAD

**Issue by AlainBaslter** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#47]
I cannot find examples of handling grid events.

How does my ViewModel know when a row has been selected?
How do I detect what rows were selected (multiple) and get to the underlying data?
How do I pick up row double clicks in my VM?

I tried those...

'selectedRecords', 'selectedRowIndex', 

e-selected-records.bind='propOnVM'
e-selected-row-index.trigger='methodOnVM()'

No go.

A few examples of using grid events would be great.

Thanks

**Comment by karthickthangasamy** [comment]
@AlainBaslter The events hooked to Syncfusion widgets through attributes by appending prefix `e-on-` with widget's original event name(e-on-event-name.delegate). For example, The `selectedRecords` event will be hooked like the below.

```
e-on-selected-records.delegate='methodOnVM($event)'
```

We can fetch the data from the Syncfusion widget's event using `$event.detail` like the below code snippet.

```
.....

methodOnVM(event){
   //get the details from here event.detail
}

.....
```

Help site: https://help.syncfusion.com/aurelia/
