### ISSUE TITLE
Chart size relative to it's container not working when using percentages

### ISSUE THREAD

**Issue by kbulte** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#48]
With the regular syncfusion web components it is possible to specify the chart size in percentage by using the size property. [documentation](https://help.syncfusion.com/js/chart/chart-dimensions#setting-size-relative-to-the-container-size)

When I try this in the essential js playground (web component without aurelia) this works [syncfusion playground](http://jsplayground.syncfusion.com/cxptt5xh)
![image](https://cloud.githubusercontent.com/assets/1887008/22198510/21399756-e157-11e6-83db-9e386b1b26e7.png)

When we use the chart component in an aurelia project and set the size via the bindable size property we get no errors but the chart is not rendered. We have the same behavior in [gistrun](https://gist.run/?id=15053c8e35e734f58aeb14d3b82faca9)

![image](https://cloud.githubusercontent.com/assets/1887008/22198638/acbb05da-e157-11e6-9924-e6615ac531ab.png)

**Comment by karthickthangasamy** [comment]
@kbulte We need `display:block` property for the custom element `<ej-chart>` to get actual height and width. 

I have updated the changes, please check the [gistrun](https://gist.run/?id=15053c8e35e734f58aeb14d3b82faca9)
