### ISSUE TITLE
define Syncfusion JavaScript collection installation

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#5]
**_Before starting real activity related to this issue, I propose a solid discussion - by adding comments / question to this page.**_

---

---
##### Task 2: define all needed types of bridge installaton for application developers (bridge users)

---
### Details

For the obvious reasons (compatibility with other bridges) this task should follow the **[Kendo Installation pages](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation)** information, shown below:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/14404223/b4cf9e22-fe3e-11e5-9b0f-98ee7f6ae3ef.png"></img>
 <br><br>
Installation instructions for bridge users
</p>

<br><br>

Note that due to the relative complexity of Telerik's sales model (kendo-core is free and can be obtained using bower, kendo-pro has to be purchased or already owned) we provided three installation methods. Based on these methods, we provide different tutorials (see http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/1._introduction) for more details

I believe that we should start from : https://github.com/syncfusion/JavaScript-Widgets and define the project structure using "vendors" approach - just like we did with KendoUI bridge below:

<p align=center>
  <img src="https://cloud.githubusercontent.com/assets/2712405/14404293/fec3c228-fe3f-11e5-9b0f-b275986967df.png"></img>
 <br><br>
Project structure
</p>

**Comment by bharathm03** [comment]
@adriatic this is the structure, I'm planning for vendor folder to align with "syncfusion/javascript-widgets" repo. 

![image](https://cloud.githubusercontent.com/assets/2254476/14429450/1af86232-001b-11e6-9e5c-d38a1097aef8.png)

let me know your comments on this

**Comment by adriatic** [comment]
**A few comments**

Please consider using the word `vendors` for compatibility reasons (this is a very low importance request and will leave it to you if it violates any Syncfusion branding). The reason I mention it here is to make the Aurelia developer's life easier - check the **[KendoUI bridge installation page](http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation)** which describes how to add the KendoUI SDK to the bridge and try to make it as similar as possible

As you will see we support three different modes of KendoUI SDK installation - so we should discuss how do you plan to do this with some additional level of details.

Although this might not happen often, our effort to make Aurelia developers happy should include the possibility to allow them to use more than one bridge in a single app (we have such cases already) so uniformity is at premium

**Comment by bharathm03** [comment]
Ok @adriatic. i will correct the folder name to "vendors"

**Comment by bharathm03** [comment]
@adriatic we have merged the `vendors` folder
