### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by AlainBaslter** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#50]
Just some feedback on what I observed grabbing latest as of today.
Steps:
Download zip
Unzip
npm install
jspm install

Got this error on above step...

err  Error: EPERM: operation not permitted, rename 'C:\Users\adespaignet\AppData\Local\.jspm\packages\npm\aurelia-framework@1.0.3\dist\amd' -> 'C:\Users\adespaignet\AppData\Local\.jspm\packages\npm\.tmp-aurelia-framework@1.0.3'
         at Error (native)

warn Installation changes not saved.

Ignored it and went on to 

gulp watch

Everything built and ran

No idea what that glitch above is about.

I am admin. This folder 

C:\Users\adespaignet\AppData\Local\.jspm\packages\npm\.tmp-aurelia-framework@1.0.3

Is marked read only.
I have full control there and here
C:\Users\adespaignet\AppData\Local\.jspm\packages\npm\aurelia-framework@1.0.3\dist\amd

Node is 6.3.1

Clear npm cache?
False alarm? Ignore it? Builds and runs. Pretty odd.

**Comment by AlainBaslter** [comment]
Must be my setup. Tried it on a clean machine Windows 10 32 bit. All good.

**Comment by karthickthangasamy** [comment]
@AlainBaslter 👍

**Comment by adriatic** [comment]
This is a pretty frequent event that can be attributed to several different causes, including for example a running virus protection program, that might be having the handle on that same file that the installer wanted to rename.
