### ISSUE TITLE
Cannot set property 'unobtrusive' of undefined

### ISSUE THREAD

**Issue by stuartbloom** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#55]
I recently installed the bridge using npm.  everything seems to work, however I get the following error:

![image](https://cloud.githubusercontent.com/assets/7871566/24409967/b03bbc32-13c9-11e7-8203-6fd9f60855f4.png)

Looking at the code, this is the line it is failing on:

![image](https://cloud.githubusercontent.com/assets/7871566/24409991/c283dde8-13c9-11e7-85b8-bc787861a694.png)

Does anyone know what I may be missing?

Thanks in advance

**Comment by karthickthangasamy** [comment]
@stuartbloom The `jquery-validation-unobtrusive` script is loaded before the `jquery-validation` script loading. Within a short span of time, again the `$jQval` is available and everything works well. As for now, we can ignore this error.

For your kind information, we are working on to removal of `jquery-validation-unobtrusive` script, we can expect a release in near future to overcome this console error completely.

**Comment by stuartbloom** [comment]
@karthickthangasamy thanks for the information.  When the upgrade that fixes this error is done, will you be able to let me know?

Thanks again

**Comment by karthickthangasamy** [comment]
@stuartbloom Sure, I will update you the details once we published the next version of `aurelia-syncfusion-bridge`.

**Comment by stuartbloom** [comment]
👍 thanks
