### ISSUE TITLE
ejGrid selectedRows member

### ISSUE THREAD

**Issue by stuartbloom** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#57]
Hi there, I have tried to bind to the e-selected-rows member for the grid, however, it nether gets set when traversing the grid, or has any effect of row selection when changed.

Is it possible to bind the grid to a property of the view model and have the grid "select" that row?

i.e. I have a grid with data, and I have a row selected that is associated with primary data key of 5.  When I refresh the data, I want to re-select that row.

Thanks in advance

**Comment by AlainBaslter** [comment]
I also ran into issues with getting the selected row. It does not seem to fire.
Here is what I am doing... in the view...on the ej-grid element
           e-on-record-double-click.delegate="onRecordDoubleClick($event.detail)"
Then in the view model...
    private onRecordDoubleClick(params) {
        logger.debug("onRecordDoubleClick");
        logger.debug(params);
    }
I don't like it either because it is not "MVVM" ish. 
I'd prefer having nothing to do with the UI in the VM and I'd like to have a bound selectedRow changing dynamically.

**Comment by stuartbloom** [comment]
That's what i have at the moment, but it's only one way, i.e. view to view model, but there is no way of binding from the view model to the view

**Comment by AlainBaslter** [comment]
Well e-on-record-double-click fires, surely e-selected-rows should fire too but as we have seen it does not. If that works it would be ideal as it gives an array of the selected row "models" back to the VM.

**Comment by adriatic** [comment]
Since it is the Syncfusion team that assists with Syncfusion user issues, I would suggest to upgrade the **[catalog application](http://aurelia-ui-toolkits.github.io/demo-syncfusion/#/help)** and offer the same functionality described at http://aurelia-ui-toolkits.github.io/demo-kendo/#/help (check the GistRun section). 

Presenting your problem in the form of a gist makes support folks very happy 😏

**Comment by AlainBaslter** [comment]
rowSelected fires here
http://js.syncfusion.com/demos/web/#!/bootstrap/grid/events
The catalog app does not cover grid events indeed. 
Since I need this functionality I'll take a look and see if I can figure it out.

**Comment by stuartbloom** [comment]
@AlainBaslter that's great, however, imagine you want to select one of those rows by the clicking if a button.

**Comment by AlainBaslter** [comment]
@stuartbloom I see what you are wanting to do i.e. go from the VM and pre-select some rows on the grid.
I am not sure ej-grid even supports that. Does it say it does in the Syncfusion docs?
Well I got the latest code and built it. I wired in an Events sub-section under the Grid demo page in the samples. Next up is I will wire in all events and see what fires and what does not.

**Comment by stuartbloom** [comment]
@AlainBaslter the API details two members, selectedRecords and selectedRowIndex. I think the latter looks like a good candidate.

**Comment by stuartbloom** [comment]
@adriatic, @AlainBaslter Just wondering, are there any examples of using e-selected-row-index (selectedRowIndex) on a grid?

If not then I may be able to achieve what I wan by working with the ejGrid object in the DOM, although I don't want to start including jQuery in my VMs.  If I have to go down that route, is it possible to get the ejGrid object via a bound property?

Thanks in advance

**Comment by karthickthangasamy** [comment]
@stuartbloom @AlainBaslter 

We have analyzed the query and we suspect that you want to maintain the selected record after refreshing the data in grid. 

In the external button click, we have refresh the grid data source and by using `actionComplete` event of ejGrid, we can select rows of ejGrid control. 

Refer the below code example. 

```html
<template> 
    <button id="button" ej-button e-on-click.delegate="refreshData()">Button</button> 
    <div> 
        <ej-grid id="Grid" e-data-source.bind="dataSource" e-selection-type="multiple" e-selected-row-indices.bind="selectedRows" e-allow-paging=true e-on-action-complete.delegate="eventactionComplete($event.detail)"> 
            <ej-column e-field="OrderID" e-is-primary-key="true"></ej-column> 
            <ej-column e-field="EmployeeID"></ej-column> 
            <ej-column e-field="CustomerID"></ej-column> 
        </ej-grid>          
    </div> 
</template> 

```

```javascript
export class Grid { 
     
   constructor() { 
       this.dataSource = dataSource, 
       this.selectedRows = [1,4,5]; // select the rows while initial rendering 
                         
   } 
   eventactionComplete(e){ // after refreshing the data in grid , we can select the grid rows 
 
       if(e.requestType = "refresh" && !this.initialRender) 
 
             this.selectedRows = [1,4,5];         
   } 
   refreshData(){ 
 
        this.dataSource =  dataSource2; 
   }           
} 
```

Refer the help documentation. 

**Link**: https://help.syncfusion.com/api/js/ejgrid#events:actioncomplete 

**Link**: https://help.syncfusion.com/api/js/ejgrid#members:selectedrowindex

**Comment by stuartbloom** [comment]
@karthickthangasamy That is great, just what I am after.

Thanks :)
