### ISSUE TITLE
finish the creation of the `demo-syncfusion` application 

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#6]
This task is a remainder that every Aurelia-XXX bridge has the associated catalog application, hosted in github as `gh-pages` based website. See http://aurelia-ui-toolkits.github.io/demo-kendo as the example.

The repository for that http://aurelia-ui-toolkits.github.io/demo-syncfusion  already exists  **[here](https://github.com/aurelia-ui-toolkits/demo-syncfusion)**

**Comment by bharathm03** [comment]
@adriatic information about `build` is folder is missing in demo-syncfusion readme page, as for us our understanding. We need to create bundler script for syncfusion and need copy the `build` folder as well to `demo-syncfusion` excluding development related files like test, lint etc.

also, we need to derive `deploy` gulp script from demo-kendo. Is this correct?

**Comment by adriatic** [comment]
The [demo-syncfusion](https://github.com/aurelia-ui-toolkits/demo-syncfusion) repository is not finished as you realized already. Even the most basic [How to run](https://github.com/aurelia-ui-toolkits/demo-syncfusion#how-to-run) set of instructions is just the (Telerik based) placeholder for the real instructions.

I would recommend to delay [this task](https://github.com/aurelia-ui-toolkits/demo-syncfusion#how-to-run) until such time when there is something to show in this catalog. The `deploy` task is hard, mostly because the application bundling is very error prone and takes time for even someone with experience to do right. As you realize, the "standalone" application like demo-syncfusion, is hosted on GitHub as a `gh-pages` project and it cannot have its huge runtime modules organized in the form of jspm_files and syncfusion's `ej-` modules unbundled.

**Comment by bharathm03** [comment]
@adriatic ok, i will hold this task for now.

**Comment by karthickthangasamy** [comment]
Hi @adriatic ,

We have completed the below list of controls for Syncfusion Aurelia catalog application.

**Grids**
1. Grid

**Data Visualization**
1. Chart
2. Gantt
3. Schedule
4. Diagram 
5. Circular Gauge
6. Linear Gauge
7. Digital Gauge
8. Bullet Graph
9. Range Navigator
10. Barcode 
11. Kanban Board

**Layout**
1. Splitter
2. Dialog
3. ListView

**Editors**
1. DatePicker
2. DateTimePicker
3. TimePicker
4. Autocomplete
5. RadialSlider

**Navigation**
1. Ribbon 
2. Rotator
3. Tab
4. Menu 
5. ListBox

We are working on the sample implementation of remaining Syncfusion Aurelia components. We also completed, the [demo-syncfusion](https://github.com/aurelia-ui-toolkits/demo-syncfusion) application and need to ensure the `demo-syncfusion` with Syncfusion Aurelia bridge source. Could you please publish the bridge source in `npm` and provide us beta link for testing purpose.?

Thanks,
Karthick T

**Comment by adriatic** [comment]
Thanks for the update - it seems that you are doing well :-). I am a bit busy for a day or two and will return back to this project right after that. In the mean time, please answer the following question:

You are saying that you finished the [demo-syncfusion](https://github.com/aurelia-ui-toolkits/demo-syncfusion) application -- but that repository has only the README file and even that file is incorrect shown below

![image](https://cloud.githubusercontent.com/assets/2712405/15480297/c7282c70-20f2-11e6-80d0-693c0a614761.png)

I do not believe that we can get Syncfusion code from Telerik, using Telerik's credentials :-), right?

Please provide this missing information - either by sending me it via email or on our Gitter chat room

**Comment by karthickthangasamy** [comment]
The [demo-syncfusion](https://github.com/aurelia-ui-toolkits/demo-syncfusion) catalog-app implemented.
