### ISSUE TITLE
Nested properties in ej-xxx

### ISSUE THREAD

**Issue by AlainBaslter** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#66]
In the example below can nested view model properties not be used?

`<input ej-tooltip="e-content.bind:tip" ej-numeric-textbox="e-width.bind:width;e-value.bind:model.value;e-watermark-text.bind:model.watermark" />`

Actually I have a lot more `e-xxx.bind=someViewModelProperty` in there not shown.
As long as the properties are directly on the view model itself (not nested) it works.

It appears that when they are nested it does not work. 
Can it be made to work? If so how?

This works when using straight HTML5 <input>

`<input type="text" value.bind="model.value" placeholder.bind="model.placeHolder" />`

Aurelia supports nested binding, custom attribute 

> ej-numeric-textbox

 does not?

Can I use those e.g. `e-width.bind:width` like this...

`e-width.bind="width"` i.e. not inside `ej-numeric-textbox="not here"` string like for the grid?

It must be a limitation of the bridge?

**Comment by mariaantony-gnanasekaran** [comment]
@AlainBaslter Yes , you can use nested view-model properties inside aurelia-syncfusion-bridge custom attribute.

Refer the below gist

**https://gist.run/?id=0cf33b14c00ede36898a6733597bdf31**

If you are still facing the issue , Please share your simple Aurelia sample in gist or GitHub repository.

**_Query: Can I use those e.g. e-width.bind:width outside the custom attribute ?_**

As per Aurelia standards, custom attribute properties should be used only inside the wrapper. So, you can’t use e-width.bind:width outside the custom attribute. Refer the below link to know more about custom attribute

**http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-attributes/7**

**Comment by AlainBaslter** [comment]
@mariaantony-gnanasekaran Thanks very much that was very useful. Turns out I made a mistake in initializing my model. Indeed it works nested.
