### ISSUE TITLE
Scheduler two way data binding

### ISSUE THREAD

**Issue by jbyl** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#69]
I was wondering if the ejSchedule widget supports two way binding to a collection of appointments stored in the view model, like this:
```html
<ej-schedule dataSource.bind="appointments">
</ej-schedule>
```
I know that this is allowed:
```html
<ej-schedule e-appointment-settings.bind="schedulerData"></ej-schedule>
```
but in this case the appointments stored in the view model don't seem to be updated whenever a user adds a new one.

**Comment by karthickthangasamy** [comment]
@jBylinski In native Aurelia, there is no two way binding support for complex property and in Schedule, the data source property will be like `appointmentSettings.dataSource` (which is complex property), therefore two way binding is not possible for Scheduler data source.
