### ISSUE TITLE
TypeScript syntaxes used in JS files

### ISSUE THREAD

**Issue by bharathm03** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#7]
Found some typings in JS file. As per mail conversion with @Thanood, 

> This was done to provide babel-dts-generator with the necessary information to be able to generate a .d.ts typescript definition file.

For generating d.ts file, do we need to consider typings in wrapper component file also? Also, i tried to get the documentation for `babel-dts-generator`, which is empty in github repo.

**Comment by adriatic** [comment]
_The information you request (and a lot more) is provided **[here](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki#4-bridge-developers-notes)** and you were supposed to read this already :-)_

As it is really difficult to serialize all of the available information in a sequential set of articles, I expected the need to "iterative refinement" so, here is my second attempt to clarify this initial approach to creating the bridge:

**[Aurelia-Syncfusion bridge](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge)** github repo has only the needed minimum of the infrastructure to be able to start building the Aurelia-Syncfusion bridge. 

In other words, adding **bridge infrastructure code** (content of the https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/tree/master/src folder) and **bridge catalog application code** (everything in https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/tree/master/sample folder) is what **you will be doing until everything is done**. 

In the course of this project, you should look at the Aurelia-KendoUI **bridge infrastructure code** (content of the https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/src folder) and **bridge catalog application code** (everything in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/sample folder) as the model for your own work (most of that code is to be copied verbatim)

**Important node** 
All of the documentation for bridge developers (Syncfusion team in this case) is available in the **[Aurelia-KendoUI bridge catalog application](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/notes_on_the_bridge/1._introduction)** help section - and this section includes the documentation for `bable-dts-generator` that you are asking about above.

### Summary

Task of creating the Aurelia-Syncfusion bridge consists of **copying small chunks of the code** from **[KendoUI repo](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge)** to **[Syncfusion repo](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge)**.

**Note** that creating Syncfusion bridge **includes** the creation of the Syncfusion bridge catalog application (task https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/6).

**_Please do not hesitate to extend this conversation with more questions if needed.**_

**Comment by Thanood** [comment]
More specifically, the dts-generator is described [here](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/Babel-DTS-generator). To be fair: there seems not to be an exhaustive list of available options (which would be very convenient to know how to tweak the generator). I've tried to find these, too.

**Comment by bharathm03** [comment]
@Thanood and @adriatic thanks
