### ISSUE TITLE
importing ejChart causing typescript error. 

### ISSUE THREAD

**Issue by irsali** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#71]
import { ejChart  } from 'aurelia-syncfusion-bridge';

Simple issue to replicate import ejChart and typescript typings start complaining, also about not found some aurelia components.

If using .js file. it works fine.

Not sure: is it a right place to raise typescript typings issue.

**Comment by sanjithkesavan** [comment]
Hi @irsali ,

We will check this and update.

Regards,
Sanjith.

**Comment by sanjithkesavan** [comment]
Hi @irsali ,

Thanks for your patience. We have analyzed your query and tried to replicate the reported issue at our side. But, reported issue not reproduced at our end. In the below link, we have attached sample for your reference. 
Sample link: http://www.syncfusion.com/downloads/support/directtrac/186301/ze/Chart-2016301760 

Please follow the below link to getting started with our chart control.
https://help.syncfusion.com/aurelia/chart/getting-started 

Still the query is not clear please provide us more details about the issue you are facing. Or else please provide the sample in which reported issue is reproduced. This information would be helpful for us to provide the solution to meet you requirement.

Please let us know if you have any concern.

Thanks,
Sanjith.

**Comment by irsali** [comment]
Hi @sanjithkesavan 

I have reviewed your sample link project. Although, i could not run it. I have observed the code, it is using Javascript. The issue exist only for Typescript.

I have added a repository, if you wanna see it. [https://github.com/irsali/aurelia-syncfusion-typescript](https://github.com/irsali/aurelia-syncfusion-typescript)
with error screen in readme file. 
Also Note, project is running good but the error exist.

**Comment by dharanidharandharmasivam** [comment]
Hi @irsali ,

We are checking in this and will update you.

Regards,
Dharani.

**Comment by karthickthangasamy** [comment]
@irsali The `aurelia-syncfusion-bridge` is an plugin which can be imported in `main.ts` ([here](https://github.com/irsali/aurelia-syncfusion-typescript/blob/master/src/main.ts#L8))

```typescript
.plugin('aurelia-syncfusion-bridge', plugin => plugin.ejChart())
```

Could you please share more information about importing `ejChart` in sample level, which help us to provide you prompt solution at the earliest.?
