### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#74]
Hey there, I have a suggestion:

It might be good to use aurelia-logging to log the configuration objects that are used to initialize controls: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/widget-base.js#L211. This makes debugging issues far easier. E.g. If I make a a typo (I used k-label but needed k-labels) I can look in the console and see that the labels property is missing when the control is initialized.

Also, what is your opinion on decoupling syncfusion from the syncfusion bridge? The import statements in every wrapper causes the module loader / bundler to bundle the syncfusion control. That makes bundling (and tracing in case of the aurelia cli) pretty slow, especially if you use the entire suite. If the bridge wouldn't do imports of syncfusion then the developer could choose how to pull in syncfusion, either through a module loader, script tag (and local hosted syncfusion) or use syncfusion's CDN

Thanks for your work on this!

**Comment by karthickthangasamy** [comment]
@JeroenVinke Thanks for your valuable suggestion.

We will implement the logger in bridge.

Regarding decouple Syncfusion from the bridge, which leads to breaking changes to bridge users. I will check with management and update you further details at the earliest.

Thanks.!

**Comment by gregoryagu** [comment]
I believe this can be closed now.

https://help.syncfusion.com/aurelia/release-notes/v15.4.0.17?type=all#common-breaking-changes
