### ISSUE TITLE
i18n problems

### ISSUE THREAD

**Issue by pbgc** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#76]
Hi,

I have a perfectly running example of a grid using remote data and bundled with aurelia cli.
I tried to apply this: https://help.syncfusion.com/aurelia/getting-started/globalization-localization to test localization but I'm having problems (tried syncfusion-ej-global and syncfusion-ej-global-all - syncfusion-ej-global-all is that I really want because my language is not is syncfusion-ej-global)

In aurelia.conf I added, after the other bridge entries:

```
{
            "name": "syncfusion-ej-global",
            "path": "../node_modules/syncfusion-ej-global/",
            "main": "syncfusion-ej-global",
            "resources": [
              "**/*.js"
            ]
},
```
and in app.html I have:

```
<template>
    <require from="syncfusion-javascript/Content/ej/web/ej.widgets.core.bootstrap.min.css"></require>
    <require from="syncfusion-javascript/Content/ej/web/bootstrap-theme/ej.theme.min.css"></require>
    <require from="syncfusion-javascript/Content/ej/web/responsive-css/ej.responsive.css"></require>

    <div>
        <ej-grid e-data-source.bind="remoteData"

                 e-locale="de-DE"
.........................
      </div>           
</template>
```

and in app.js
```
import 'syncfusion-ej-global/i18n/ej.culture.de-DE.min.js'; 
```

When doing au.run i get:

Starting 'writeBundles'...
Tracing app...
 ------- File not found or not accessible ------
| Location: /Users/pbeck/Development/projects/JS/sf-test2/syncfusion-ej-global/i18n/ej.culture.de-DE.min.js
| Requested by: /Users/pbeck/Development/projects/JS/sf-test2/src/app.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package

Thanks in advance!

PS: when trying syncfusion-ej-global-all I get a LOT more errors

**Comment by mariaantony-gnanasekaran** [comment]
Hi @pbgc ,

Please remove  **ej.core.min** dependency from all **node_modules/syncfusion-ej-global/l10n/*.js** files like the below one

**[ej.localetexts.de-DE.min.js]**

```
(function(n){typeof define=="function"&&define.amd?define([],n):n()})(function(){(function(n,t){var
```
> If you are using **syncfusion-ej-global-all** package, Please do the same

This issue will be fixed soon and we will republish `syncfusion-ej-global` and `syncfusion-ej-global-all` packages as soon as possible.

After removing ej.core dependency, Follow the below steps

* In `aurelia.json` file , Add **syncfusion-global bundle** in Array of Bundles like the below code snippet

```
 {
        "name": "syncfusion-global.js",
        
        "dependencies":[
          {
            "name": "syncfusion-ej-global",
            "path": "../node_modules/syncfusion-ej-global/",
            "main": false,
            "resources": [
              "i18n/ej.culture.de-DE.min.js",
              "l10n/ej.localetexts.de-DE.min.js"
            ]
          }
        ]
      }

```
Note: If you want to use all culture file, Then modify syncfusion bundle resources as the below one.

```

 "resources": [
              "i18n/*.js",
              "l10n/*.js"
            ]

```

Then import localization and globalization file in your application like the below code snippet.

```
import 'syncfusion-ej-global/i18n/ej.culture.de-DE.min';
import 'syncfusion-ej-global/l10n/ej.localetexts.de-DE.min';

export class App {
  constructor() {
    this.edit = { allowAdding: true, editMode: ej.Grid.EditMode.Dialog };
    this.toolbar = { showToolbar: true, toolbarItems: [ej.Grid.ToolBarItems.Add] };

    this.data = [{
      CustomerName: "VINET", OrderDate: new Date(8364186e5), Freight: 32.38
    },
    {
      CustomerName: "TOMSP", OrderDate: new Date(836505e6), Freight: 11.61
    },
    {
      CustomerName: "HANAR", OrderDate: new Date(8367642e5), Freight: 65.83
    }]
  }
}

```

**Comment by pbgc** [comment]
still no luck.
I'm having this error with au run:

Tracing syncfusion-ej-global...
error /Users/pbeck/Development/projects/JS/sf-test2/node_modules/syncfusion-ej-global/false.js

**Comment by pbgc** [comment]
Please ignore my last comment ... I will try again to test.

**Comment by pbgc** [comment]
Please ignore my last comment ... I will try again to test.

**Comment by pbgc** [comment]
I did everything like you said.
I don't have any error on the build and in the build log I have:

Writing app-bundle.js...
Writing syncfusion-global.js...
Writing vendor-bundle.js...

I don't have any error on the browser javascript console and the code runs well ... BUT without any i18n .... everything is still in english

**Comment by pbgc** [comment]
Another problem:

As the standard way of localizing is not working ... I tried to put: 

e-locale="pt-PT"

on the grid definition and in app.js:

```
        ej.Grid.Locale['pt-PT'] = {
            EmptyRecord: 'Não existem registos',
            GroupDropArea: 'Arraste para aqui um cabeçalho de coluna para agrupar pela coluna',
            DeleteOperationAlert: 'Nenhum registo seleccionado para a operação de apagar',
            EditOperationAlert: 'Nenhum registo seleccionado para a operação de edição',
            SaveButton: 'Gravar',
            CancelButton: 'Cancelar',
            EditFormTitle: 'Detalhe de ',
            GroupCaptionFormat: '{{:headerText}}: {{:key}} - {{:count}} {{if count == 1}} item {{else}} itens {{/if}}',
            UnGroup: 'Clique para desagrupar',
            StringMenuOptions: [{ text: 'Começa com', value: 'startswith'}, { text: 'Acaba com', value: 'endswith'}, { text: 'Contêm', value: 'contains'}, { text: 'Igual', value: 'equal'}, { text: 'Diferente', value: 'notequal'}],
            NumberMenuOptions: [{ text: 'Menor', value: 'lessthan' }, { text: 'Maior', value: 'greaterthan' }, { text: 'Menor ou Igual', value: 'lessthanorequal' }, { text: 'Maior ou Igual', value: 'greaterthanorequal' }, { text: 'Igual', value: 'equal' }, { text: 'Diferente', value: 'notequal' } ],
            Filter: 'Filtrar',
            Clear: 'Cancelar',
            FilterMenuCaption: 'Valor Filtro',
            NumericTextBoxWaterMark: 'Introduza Valor',
            DatePickerWaterMark:"Seleccione data"
        };
        ej.DateTimePicker.Locale["pt-PT"] = {
            watermarkText: 'Introduza Data'
        };
        ej.Autocomplete.Locale['pt-PT'] = {
            emptyResultText: 'Sem sugestões'
        };
        ej.NumericTextbox.Locale['pt-PT'] = {
            watermarkText: 'Introduza Valor'
        };
        ej.Pager.Locale['pt-PT'] = {
            pagerInfo: '{0} de {1} paginas ({2} itens)',
            firstPageTooltip: 'Ir para primeira página',
            lastPageTooltip: 'Ir para última página',
            nextPageTooltip: 'Próxima Página',
            previousPageTooltip: 'Página Anterior',
            nextPagerTooltip: 'Próximo Pager',
            previousPagerTooltip: 'Pager Anterior'
        };
```

This works! (while not optimal! What it would be great is to be able to use the standard synfusion i18n/i10n) but has some problems! (I don't know if the standard i18n/i10n will not also have .. because never been able to use it):

- In the grid filter menu ... the watermarkText for Numeric and Datetime/Date are not being localized (see attached image for the Numeric)

![captura de ecra 2017-09-11 as 17 21 57](https://user-images.githubusercontent.com/180825/30285552-61e00aae-9716-11e7-8873-1eff0755a9b3.png)

**Comment by mariaantony-gnanasekaran** [comment]
@pbgc ,

We have prepared sample for you reference. Refer to the below attached sample.

[sample ](http://www.syncfusion.com/downloads/support/directtrac/general/ze/syncfusion-aurelia-658829748.zip)

Remove  **ej.core.min** dependency from **node_modules/syncfusion-ej-global-all/l10n/ej.localetexts.pt-PT.min.js** file like the below one.

**[ej.localetexts.pt-PT.min.js]**

```
(function(n){typeof define=="function"&&define.amd?define([],n):n()})(function(){(function(n,t){var 
```
> If you are using any other language, Please do the same

You don't need to manually set locale property. You can utilize inbuilt Syncfusion Localization.

We have also checked water mark with locale property. It works as expected. Refer the above attached sample.

If you are still facing this issue, share your sample with us.

**Comment by pbgc** [comment]
thank you very much for your sample!
I just tried but while the watermark indeed is working (I still not understand why my version didn't) you sample is not localized here! (see attachment).

- npm install
 - In ej.localetexts.pt-PT.min.js I removed: "(function(n){typeof define=="function"&&define.amd?define([],n):n()})"
- au run

![captura de ecra 2017-09-12 as 11 02 06](https://user-images.githubusercontent.com/180825/30320332-3617bda6-97aa-11e7-8989-5702395fe686.png)

**Comment by mariaantony-gnanasekaran** [comment]
Hi @pbgc ,

Don't remove the line. Just remove the below marked syntax.

![image](https://user-images.githubusercontent.com/23378261/30320530-8d721d96-97d0-11e7-920b-015e77e7bf8f.png)

or replace the below attached file in **node_modules/syncfusion-ej-global-all/l10n**  location.

[ej.localetexts.pt-PT.min.js](http://www.syncfusion.com/downloads/support/directtrac/general/ze/ej.localetexts.pt-PT.min.js204550216.zip)

**Comment by pbgc** [comment]
@mariaantony-gnanasekaran 

that nailed! Sorry ... my fault!
THANK YOU very much for all your help!

Meanwhile I just saw that the Portuguese translations are really not very good on some items ... (on some are even completely wrong). Could I help on that?

**Comment by karthickthangasamy** [comment]
@pbgc We are happy that the issue resolved 😄 .

**_Query: Regarding `Portuguese` translations_**

We used google translator for conversion across the supported language. 

We are maintaining our localized cultures in the repo [ej-global](https://github.com/syncfusion/ej-global/) . We always welcome your every effort and contribution for language translations. 👍 .

Thanks.!
