### ISSUE TITLE
aurelia-loader-webpack fails to find aurelia-syncfusion-bridge/grid/grid when aurelia-syncfusion-bridge is not in main bundle

### ISSUE THREAD

**Issue by MrBliz** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#78]
When aurelia-syncfusion bridge is placed in  'vendor' bundle and loaded via the ModuleDependenciesPlugin it fails at runtime with the following error.

`aurelia-loader-webpack.js:187 Uncaught (in promise) Error: Unable to find module with ID: aurelia-syncfusion-bridge/grid/grid
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:187)
    at step (aurelia-loader-webpack.js:36)
    at Object.next (aurelia-loader-webpack.js:17)
    at aurelia-loader-webpack.js:11
    at new Promise (<anonymous>)
    at 43.__awaiter (aurelia-loader-webpack.js:7)
    at WebpackLoader.43.WebpackLoader._import (aurelia-loader-webpack.js:152)
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:252)
    at step (aurelia-loader-webpack.js:36)
    at Object.next (aurelia-loader-webpack.js:17)`

Reproducible example here

https://github.com/MrBliz/aurelia-syncfusion-dotnet/tree/e284f9b10342e42e92a8e405737b67288dfa6796

**Comment by karthickthangasamy** [comment]
@MrBliz Thanks for your interest in Syncfusion Products.

We are able to reproduce the issue at our end. We will investigate and provide you further details as much as earlier.

Thanks.

**Comment by karthickthangasamy** [comment]
@MrBliz Thanks for your patience. 

The issue resolved with the below configuration in `webpack.config.vendor.js` file.

```javascript
new AureliaPlugin({ aureliaApp: undefined })
```
You can refer the changes from [here](https://github.com/karthickthangasamy/aurelia-syncfusion-spa/commit/835222ab2335ec77c38d79b059655ecbe9c40e4e).

[Sample](https://github.com/karthickthangasamy/aurelia-syncfusion-spa/)

>You have to run `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js` for bundling the `aurelia-syncfusion-bridge` into vendor bundle.

Thanks.!!

**Comment by MrBliz** [comment]
@karthickthangasamy Fantastic, thank you.
