### ISSUE TITLE
Implement ejmenu

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#8]
widget definition: https://www.syncfusion.com/products/javascript/ejmmenu

catalog examples: http://js.syncfusion.com/demos/web/#!/azure/menu/defaultfunctionalities

**Comment by karthickthangasamy** [comment]
@bharathm03 ejMenu  widget for Aurelia implementation has been completed and also ejMenu custom attribute configured for catalog application root control navigation. Please find the pull-request page as below.

https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/pull/10

Thanks,
Karthick T

**Comment by bharathm03** [comment]
@karthickthangasamy  Can you close the completed issues?

**Comment by karthickthangasamy** [comment]
The ejMenu Aurelia component implemented
