### ISSUE TITLE
The Demo Site is currently Down

### ISSUE THREAD

**Issue by gregoryagu** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#85]
I have tried several times today to get to the demo site, but it never loads.

http://aureliajq.syncfusion.com/

No messages are logged to the console, and the network tab gives no messages or info.

**Comment by karthickthangasamy** [comment]
Hi @gregoryagu : The site is down for maintenance. Now the site is up.

[https://aureliajq.syncfusion.com/](https://aureliajq.syncfusion.com/)
